### ISSUE TITLE
Add a function that creates a data.frame with candidate detection functions

### ISSUE THREAD

**Issue by fsdias** [dill/Distance2#62]
The table would list the "key function", adjustment terms, AIC/AICc, number of parameters, results from goodness of fit tests. E.g.

df_select(DF1, DF2, DF3,...)

The result would be a data.frame that looks like this table:

![screenshot from 2015-09-30 09 24 15](https://cloud.githubusercontent.com/assets/5689181/10188319/48df8e54-6756-11e5-9df9-b06d246626f5.png)

**Comment by dill** [comment]
Does `summarize_models` do what you want here?

See the "Model selection" section of http://converged.yt/RDistanceBook/distance-moredf.html for more details.

**Comment by fsdias** [comment]
Great, yes that's exactly what I was looking for. I would only add test statistics and p-values form GOF tests. If you don't think GOF results should be included in summarize_models() feel free to close this issue.

**Comment by dill** [comment]
I've closed this and made a separate, more specific issue in #63. Thanks for the suggestion!
